biomaj:
    config: '/home/osallou/Development/NOSAVE/genouest/global.properties'

redis:
    host: '127.0.0.1'
    #host: '131.254.17.40'
    port: 6379
    db: 0
    prefix: 'biomajwatcher'


consul:
    host: null
    # Unique agent identifier name among biomaj downloaders
    id: 'biomaj_watcher_agent'

web:
    debug: true
    port: 5008
    local_endpoint: 'http://127.0.0.1:5000'

tls:
    key: null
    cert: null

log_config:
    'version': 1
    'formatters':
        'generic':
            'format': '%(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s'
    'handlers':
        'console':
            'class': 'logging.StreamHandler'
            'formatter': 'generic'
            'level': 'DEBUG'
    'loggers':
        'root':
            'level': 'INFO'
            'handlers':
                - 'console'
        'biomaj':
            'level': 'DEBUG'
            'handlers':
                - 'console'
    'disable_existing_loggers': False
